name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}  # Usamos el token personalizado

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get and increment version
        id: version
        run: |
          VERSION_FILE="version.txt"
          if [ ! -f $VERSION_FILE ]; then
            echo "1.0.0" > $VERSION_FILE
          fi
          VERSION=$(cat $VERSION_FILE)
          IFS='.' read -r -a VERSION_PARTS <<< "$VERSION"
          PATCH=$((VERSION_PARTS[2]+1))
          NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$PATCH"
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo $NEW_VERSION > $VERSION_FILE
          echo "New version is $NEW_VERSION"

      - name: Build Docker Image
        run: |
          docker build -t jonso18/my-api:${{ env.VERSION }} .

      - name: Push Docker Image
        run: |
          docker push jonso18/my-api:${{ env.VERSION }}

      - name: Update Kubernetes Deployment YAML
        run: |
          sed -i 's|image: jonso18/my-api:.*|image: jonso18/my-api:${{ env.VERSION }}|' k8s/deployment.yaml

      - name: Commit and push updated deployment YAML
        run: |
          git config --global user.name "John Hernandez"
          git config --global user.email "jonso18@gmail.com"
          git add k8s/deployment.yaml version.txt
          git commit -m "Update image tag to ${{ env.VERSION }}"
          git push https://github.com/JJhernandezM/myapi.git HEAD:main --force
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Usamos el token para autenticar el push
