name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Debug GITHUB_SHA
        run: |
          # Verificar si GITHUB_SHA tiene un valor
          echo "GITHUB_SHA is: ${GITHUB_SHA}"
      
      - name: Build Docker Image
        run: |
          # Crear un tag basado en el commit hash
          IMAGE_TAG=jonso18/my-api:${GITHUB_SHA}
          echo "Building Docker image with tag: $IMAGE_TAG"  # Verificar el valor de IMAGE_TAG
          # Construir la imagen Docker
          docker build -t $IMAGE_TAG .
      
      - name: Push Docker Image
        run: |
          # Verificar que el tag no esté vacío antes de intentar subir la imagen
          if [ -z "$IMAGE_TAG" ]; then
            echo "Error: IMAGE_TAG is empty"
            exit 1
          fi
          # Publicar la imagen Docker a DockerHub
          echo "Pushing Docker image: $IMAGE_TAG"  # Verificar que el valor sea correcto
          docker push $IMAGE_TAG

      - name: Update Kubernetes Deployment YAML
        run: |
          # Actualizar el archivo deployment.yaml con el nuevo tag
          IMAGE_TAG=jonso18/my-api:${GITHUB_SHA}
          sed -i 's|image: jonso18/my-api:.*|image: '"$IMAGE_TAG"'|' k8s/deployment.yaml

      - name: Commit and push updated deployment YAML
        run: |
          # Configurar el usuario de git para hacer el commit
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          # Hacer el commit del cambio en deployment.yaml
          git add k8s/deployment.yaml
          git commit -m "Update image tag to ${GITHUB_SHA}"
          git push
          
